#!/bin/sh

# install script for pkgtxt

if ! whoami | grep "^root$" >/dev/null; then
    echo "You have to be root to install pkgtxt."
    exit 1
fi

if [ -z $install_location ]; then
    install_location="/usr/local/bin"
else
    install_location="$PREFIX"
fi

echo "Copying pkgtxt to $install_location..."
cp pkgtxt "$install_location"
echo "Performing initial pkgtxt sync..."
pkgtxt sync

echo "Installation finished!"
